# Generated by Django 5.1.2 on 2024-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
