# Generated by Django 5.1.2 on 2024-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_file_ciphertext_alter_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
