# Generated by Django 5.1.2 on 2024-11-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_file_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='access_level',
        ),
    ]
